---
- name: runc | Uninstall runc package managed by package manager
  package:
    name: "{{ runc_package_name }}"
    state: absent

- name: runc | Download runc binary
  include_tasks: "../../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.runc) }}"

- name: Copy runc binary from download dir
  copy:
    src: "{{ downloads.runc.dest }}"
    dest: "{{ runc_bin_dir }}/runc"
    mode: 0755
    remote_src: true
