---

- name: set kubelet_config_extra_args options when cgroupfs is used
  set_fact:
    containerd_runc_runtime: "{{ containerd_runc_runtime | combine({'options':{'systemCgroup':'false'}}) }}"
  when: not containerd_use_systemd_cgroup
