---
registry_namespace: "kube-system"
registry_storage_class: ""
registry_storage_access_mode: "ReadWriteOnce"
registry_disk_size: "10Gi"
registry_port: 5000
registry_replica_count: 1
# name of kubernetes secret for registry TLS certs
registry_tls_secret: ""

registry_htpasswd: ""

# registry configuration
# see: https://docs.docker.com/registry/configuration/#list-of-configuration-options
registry_config:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  http:
    addr: :{{ registry_port }}
    headers:
      X-Content-Type-Options: [nosniff]
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3
